In [36]:
import pandas as pd

df = pd.read_csv(
    'orange_power_forecast_2022_daily.csv')

df.head()

,date,Random Forest,avg_wind_speed_all_stations,vector_avg_wind_speed_all_stations,avg_wind_direction,avg_wind_speed_cubed
0,time,continuous,continuous,continuous,continuous,continuous
1,meta,meta,NaN,NaN,NaN,NaN
2,2022-01-01,2.53953e+07,7.05442,6.85321,210.831,351.062
3,2022-01-02,4.2542e+07,9.18525,8.86637,229.843,774.949
4,2022-01-03,4.2318e+07,9.25733,9.19753,237.868,793.337

In [37]:
df = df[['date', 'Random Forest']]
df = df.drop(index=[0, 1]).reset_index(drop=True)

df.head()

         date Random Forest
0  2022-01-01   2.53953e+07
1  2022-01-02    4.2542e+07
2  2022-01-03    4.2318e+07
3  2022-01-04   2.03423e+07
4  2022-01-05   3.79007e+07

In [38]:
df = df.rename(columns={'Random Forest': 'Orange Model - Predicted Wind Power (kWh)'})
df['Orange Model - Predicted Wind Power (kWh)'] = df['Orange Model - Predicted Wind Power (kWh)'].astype(float).astype(int)

df["Orange Model - Predicted Wind Power (kWh)"] = df["Orange Model - Predicted Wind Power (kWh)"] * 2


df.head(10)

         date  Orange Model - Predicted Wind Power (kWh)
0  2022-01-01                                   50790600
1  2022-01-02                                   85084000
2  2022-01-03                                   84636000
3  2022-01-04                                   40684600
4  2022-01-05                                   75801400
5  2022-01-06                                   23791000
6  2022-01-07                                   49120000
7  2022-01-08                                   45968400
8  2022-01-09                                   46748800
9  2022-01-10                                    5251100

In [39]:
output_path = 'orange_power_forecast_2022_daily_clean.csv'
df.to_csv(output_path, index=False)

print(f'Saved {len(df)} rows to {output_path}')

Saved 365 rows to orange_power_forecast_2022_daily_clean.csv

In [40]:
df

           date  Orange Model - Predicted Wind Power (kWh)
0    2022-01-01                                   50790600
1    2022-01-02                                   85084000
2    2022-01-03                                   84636000
3    2022-01-04                                   40684600
4    2022-01-05                                   75801400
..          ...                                        ...
360  2022-12-27                                   58376400
361  2022-12-28                                  125234000
362  2022-12-29                                  133919000
363  2022-12-30                                   99968400
364  2022-12-31                                  143803200

[365 rows x 2 columns]